# Setup
title:               Minittt777
tagline:             'SE'
description:         'A reserved <a href="https://minittt777.github.io" target="_blank">Jekyll</a> '
url:                 https://minittt777.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              JS
  url:               https://minittt777.github.io
  email:             soltude@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

category_dir: category/
tag_dir: tag/